### ISSUE TITLE
Add read only template

### ISSUE THREAD

**Issue by greg0ire** [Padam87/AttributeBundle#31]
A template showing how to display attributes (not in a form, in a view) would be nice.

Here is the one I'm using ATM :

```html+jinja
{% for attribute in object.attributes %}
    {% if attribute.definition.id == definition.id %}
	{% if attribute.definition.options is not empty %}
	    {% for option in attribute.definition.options %}
		{% if attribute.value == option.value %}
		    {{ option.name }}
		{% endif %}
	    {% endfor %}
	{% else %}
	    {{ attribute.value }}
	{% endif %}
    {% endif %}
{% endfor %}

```

**Comment by Padam87** [comment]
@greg0ire Thank you! I think a 3.0-alpha is coming soon, I still have to document the changes, especially the breaks, I will include this example too.

If it's not too much to ask, could you check the changes in 3.0? You probably have the best understanding of this repository, even better than me, because I haven't used this in production since 2 years ago :)

https://github.com/Padam87/AttributeBundle/compare/3.0
https://github.com/Padam87/AttributeBundle/pull/30/files

Do you have any suggestions that should be in 3.0?

**Comment by greg0ire** [comment]
Ok, I'll try to give it a look this evening :)

**Comment by greg0ire** [comment]
I think [this commit](https://github.com/greg0ire/AttributeBundle/commit/4b431c9efee428547f55ee0e23cea18820b8db5a) and [this commit](https://github.com/greg0ire/AttributeBundle/commit/ab981e3ef0eba501f93f347c719cc7fb7ccb3989) should be part of 3.0
